### ISSUE TITLE
Lookup - Move the Budget to be Inline with Duration

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#119]
Let's make the Work Package lookup card a little more compact in the vertical dimension by moving the budget attribute to be on the same line as the duration attribute. You can achieve this very simply by looking up the documentation for Bootstrap description lists.

<img width="967" alt="Screen Shot 2021-01-15 at 9 32 48 PM" src="https://user-images.githubusercontent.com/51571627/104798193-39f5c700-5779-11eb-812f-d32b82f44531.png">

**Comment by RahulR100** [comment]
I think we can also move the [WBS number and name], [Duration and Budget], and [Project name and lead] to the same row to make it even more compact
