### ISSUE TITLE
Lookup - If fields from database are empty replace them with "-"

### ISSUE THREAD

**Issue by RahulR100** [Northeastern-Electric-Racing/NER-PM-Dashboard#135]
Currently when a value from the database is empty, JS reads it as null. This causes some problems when displaying tables (padding and margins are not applied correctly). Edit the project lookup function to check for empty fields (note that not all will need to be checked as some fields such as WBS number are guaranteed to exist) and replace them with "-".

**Comment by jamescd18** [comment]
Let's specifically use an em-dash, and not a standard dash. The em-dash can be copied from here: —, or you can type it with option + shift + dash on Mac.
