### ISSUE TITLE
General - Add Contributor Instructions to Readme

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#14]
Add a section to the Readme which explains the process of improving the web app. Follow each step from opening an issue all the way through to a newest production deployment of the website.

**Comment by jamescd18** [comment]
Some ideas of what needs to be detailed:
- Steps for setting up the project
- Steps for creating an issue
- Steps & naming convention for branching
- Steps & naming convention for commits
- Steps for testing code using /dev
- Steps for creating a pull request
- Steps for deploying a new version to the production server

**Comment by RahulR100** [comment]
Can I have the steps for deploying a new version to the production server I dont know how to do this and this is the last thing I need to add?

**Comment by jamescd18** [comment]
Let's make the required changes to the README on a new branch with all the other info first, then we'll explain steps for deploying to production.

**Comment by RahulR100** [comment]
Ok I have added the steps I know to a new branch.

**Comment by jamescd18** [comment]
Go ahead and open a pull request and add me as a reviewer and I'll take a look
