### ISSUE TITLE
General - Fix Bug Where "Go" Button Results In Two Executions 

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/NER-PM-Dashboard#140]
Currently, the "Go" buttons on all pages result in two executions which should not happen. This is believed to be caused by the on form submit event handler being triggered when the "Go" button is clicked, because the button is potentially being treated as the submit button for the form while also having a click event handler attached to it, thus resulting in two executions. 

For this issue, try to figure out what is causing this bug and report it by commenting below. We will address the bug in later issues. The best way to test this would be to remove the click handler and see if clicking the button still works. If it does, then we'll know that the click handler is what causes the duplicate executions. You can view the dashboard's executions [here](https://script.google.com/u/0/home/projects/1MctN1i25-vsqfdJ9jgN2F9NLfkw5_FgEC9KRVWDTae8mudXJqICMJPZS/executions).

The picture below shows two errors for a single button click: 
![image](https://user-images.githubusercontent.com/59738829/105440184-22fd1c00-5c34-11eb-989b-a14152c22b66.png)
\
\
The picture below shows two successes for a single button click and then a single success for the reload data button. The reload data button performs correctly and only results in one execution. You can tell by the time stamp of the start time being identical that they were triggered at the exact same time.
![image](https://user-images.githubusercontent.com/59738829/105440251-3f995400-5c34-11eb-91f6-662577924eb2.png)

**Comment by RahulR100** [comment]
Yes what you said is pretty much why the bug occurs. The submit on enter handler listens for a submit action on the entire form which happens to include the button. Thus when the button is clicked, both the click event handler and the form submit handler are called, invoking 2 executions. I will fix this by simply removing the button click handler. Since clicking submits the form that handler is no longer necessary.
