### ISSUE TITLE
General - Center Placeholders within Frames

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#20]
Add proper CSS styling to the placeholder content class to allow it to be centered within the data frames it sits in.

Expected Implementation:
<img width="1256" alt="Screen Shot 2020-10-15 at 10 57 38 PM" src="https://user-images.githubusercontent.com/51571627/96218564-d66dba80-0f39-11eb-8114-72a31b71b26d.png">

Current Implementation:
<img width="1210" alt="Screen Shot 2020-10-15 at 10 58 07 PM" src="https://user-images.githubusercontent.com/51571627/96218593-e6859a00-0f39-11eb-80a7-0d863c42b809.png">

**Comment by codewithvk** [comment]
Can You tell me which page you need this feature?
