### ISSUE TITLE
General - Increase Visibility of Banner Error / Success Messages

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#26]
Current implementation of bootstrap messages on the page for error and success are inserted into the top of the page and are dismissible. Unfortunately, if the user is scrolled down on the page and receives a new error message, they might be wholly unaware of it. 

We want to fix this by making error / success messages more easily noticeable for users. One potential solution is similar to when you scroll away from a text field, and then type or edit text within the field, you are automatically scrolled back up to the text field.

<img width="1039" alt="Screen Shot 2020-10-27 at 9 37 56 PM" src="https://user-images.githubusercontent.com/51571627/97391545-ae1c7f00-189c-11eb-9843-71b7bae702cd.png">

**Comment by jamescd18** [comment]
Success message example:
<img width="964" alt="Screen Shot 2020-10-27 at 9 41 39 PM" src="https://user-images.githubusercontent.com/51571627/97391772-33079880-189d-11eb-9962-5aeda39257af.png">

**Comment by mccauleyma** [comment]
As a suggestion/observation, it may be improved by placing it with respect to the screen rather than fixed to the page. I've had numerous cases where I hit submit a few times, but then realized I needed to scroll up to see the error.

**Comment by jamescd18** [comment]
Alternative solution: convert error and success messaging within the application to [Bootstrap toasts](https://getbootstrap.com/docs/4.3/components/toasts/) that are positioned as an overlay, relative to the screen instead of fixed to the page, still dismissible, and also potentially auto-hiding after a set period of time.

**Comment by jamescd18** [comment]
See LinkedIn error / success messages for a real-world usage of toasts. 
<img width="432" alt="Screen Shot 2020-10-27 at 9 55 37 PM" src="https://user-images.githubusercontent.com/51571627/97392574-56334780-189f-11eb-9e01-94f1e74a6739.png">
