### ISSUE TITLE
Dashboard - Move Page to be 2nd Tab

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#55]
Leftover tiny thing from #52 and #43. Move the Dashboard tab so that it appears immediately to the right on the "home" tab as the second tab option. This means two fixes in index.html for the top tabs and the page content tabs, then a fix in home.html to make the "pages" list reflect the same order.

**Comment by eshwaribhide** [comment]
Maybe for consistency sake, everything under "Dashboard Page Functions" in JavaScript.html can also be moved above all other page functions (so right above "Gantt page functions")

**Comment by jamescd18** [comment]
Yes, see #71
