### ISSUE TITLE
Projects - Remove Extraneous Data

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#69]
Just delete the stuff marked in red from the database spreadsheet. It's not important info.
<img width="923" alt="Screen Shot 2021-01-02 at 10 16 41 AM" src="https://user-images.githubusercontent.com/51571627/103463760-ad142d80-4ce3-11eb-85a4-18d5f9f60a9f.png">

**Comment by eshwaribhide** [comment]
I just ended up doing this.
