### ISSUE TITLE
WP Lookup - Enable Sub-Bullets for WP Descriptions

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/NER-PM-Dashboard#7]
The sub-bullets in the description section of the WP lookup tab does not work. All bullets are currently displayed on the same level.

**Comment by jamescd18** [comment]
Example of issue:
<img width="651" alt="Screen Shot 2020-10-25 at 2 04 50 PM" src="https://user-images.githubusercontent.com/51571627/97119068-0d2a9a00-16cb-11eb-9eac-06797a9a2c43.png">

Bullets that begin with "-" are supposed to be formatted as sub-bullets, but for some reason are not. See `buildUnorderedListHTML()` and `[buildListHTML()](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/76c44f059d692ad261fd92081f9ac70941780a8e/Code.js#L83)` in `Code.js` for more [details](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/76c44f059d692ad261fd92081f9ac70941780a8e/Code.js#L83).

**Comment by jamescd18** [comment]
Discovered that the issue is with newlines. Checking equality when the first thing is "\n" and you don't realize it definitely messes up the checking.
