### ISSUE TITLE
Gantt - Remove Input Group

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#81]
In its current state, the "Gantt" page has a non-functional input group the seems to tell users to search for a Gantt chart based on the WBS #. This is misleading and an inferior user experience which forces the users to know that they need to simply just hit the go button in order to get what they want.

When users hit the go button, they are presented with a frame containing a button and the Gantt chart. The button opens a modal that shows a "full-page" view of the Gantt chart.

Let's simplify things for the users and remove this unnecessary step. Remove the input group and instead replace it with the "View Full Gantt" button that already exists. This will likely involve removing old and unnecessary code that was previous used to achieve the functionality. Be sure to also edit the text on the page that tells users what to do, and potentially also the home page text.

<img width="989" alt="Screen Shot 2021-01-06 at 8 50 35 PM" src="https://user-images.githubusercontent.com/51571627/103852567-f60c0f00-5060-11eb-85b3-b0a05a4d8487.png">

**Comment by RahulR100** [comment]
I think this is required to implement issue #1

**Comment by kevinyu328** [comment]
That's true. Are we forgoing the lookup functionality of the Gantt chart for now then?

**Comment by eshwaribhide** [comment]
> That's true. Are we forgoing the lookup functionality of the Gantt chart for now then?

I believe this is a temporary fix till #1 is implemented
