### ISSUE TITLE
Reports - Refactor table display

### ISSUE THREAD

**Issue by RahulR100** [Northeastern-Electric-Racing/NER-PM-Dashboard#87]
Massive tables are currently displayed with the ability to scroll through them. This is not very user friendly. Hence, investigate the way these tables are generated and edit the page so that the table can make use of the full width of the page to see more coloumns at the same time.

**Comment by jamescd18** [comment]
Massive tables aren't the desirable UI by any means, but I don't think full-width tables is what we'd like to focus on for fixing this. Massive tables with scrolling is primarily created by cutting corners and simply dumping database tables into the UI. I'd like us to focus on building better UIs not by accommodating massive tables, but instead by rearranging tables or replacing tables with template components to better display information.
