### ISSUE TITLE
General - Make Alert Messages More Meaningful

### ISSUE THREAD

**Issue by RahulR100** [Northeastern-Electric-Racing/NER-PM-Dashboard#90]
When changing status for instance, a message that says that "Set 1.2.1 to 0.0" is less meaningful than one that says "Set status of WP 1.2.1 to 0% complete". Update all such messages to make them more meaningful.

**Comment by jamescd18** [comment]
Let's make sure to have issue titles follow the naming template for ease of reading / sorting / understanding
