### ISSUE TITLE
Projects - Add Project Status Column

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/NER-PM-Dashboard#96]
1. Create a new column in the "Projects" tab in the Database spreadsheet
2. Populate the column with "A", "I", or "C" based on:
   - "C" if all the Work Packages in the project are "C" (there are none of these as of right now)
   - "A" if the project has a Work Package which is "A"
   - "I" if the project has no Work Package which is "A"

**Comment by eshwaribhide** [comment]
This is done; can this issue be closed?
